version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - production.env
  kafka:
    image: bitnami/kafka:3.2
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    expose:
      - "9093"
    env_file:
      - production.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka

  postgres:
    image: postgres
    env_file:
      - production.env
    ports:
      - 5432:5432