datasets:
  taxi:
    column_mapping:
      categorical_features:
        - 'PULOCATIONID'
        - 'DOLOCATIONID'
      numerical_features:
        - 'TRIP_DISTANCE'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/green_tripdata_2021_01.parquet
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5